app/accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/accounts/index.html', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page="posts:index"), name='logout'),
    path('guest_login/', views.guest_login, name = 'guest_login')
]

app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from posts import views
from django.views.generic import base

urlpatterns = [
    path('posts/', include('posts.urls')),
    path('', views.top, name='top'),
    path('about/', views.about, name='about'),
    path("api/like/<int:post_id>/", views.api_like, name="api_like"),
    path('admin/', admin.site.urls),
    path('categol_list/<str:categol>/', views.categol_list, name='categol_list'),
    path('posts/<int:post_id>/', views.post_detail, name="post_detail"),
    path('posts/<int:post_id>/like/', views.like, name='like'),
    path('accounts/', include('accounts.urls')),
    path('accounts/profile/', base.RedirectView.as_view(url="/")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/posts/urls.py
from django.urls import path
from . import views



app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_posts_count/<str:username>/', views.get_posts_count, name='get_posts_count'),
    path('posts/<int:post_id>/', views.post_detail, name="post_detail"),
    path('add/', views.add, name='add'),
    path('edit/<int:post_id>/', views.edit, name='edit'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('posts/<int:post_id>/like/', views.like, name='like'),
    path("api/like/<int:post_id>/", views.api_like, name="api_like"),
    ]

app/posts/models.py
from django.db import models
from mdeditor.fields import MDTextField
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from taggit.models import Tag
from markdown import markdown

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    tags = TaggableManager(blank=True)
    published = models.DateTimeField(default=timezone.now, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='media/', blank=True)
    btc = models.CharField(max_length=100, blank=True, null=True)
    body = MDTextField()
    like = models.IntegerField(default=0)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:120]

    def get_tags(self):
        tags = list(Tag.objects.all())
        menu = {}
        for tag in tags:
            count = len(Post.objects.filter(tags__name__in=[tag]))
            if count > 0:
                menu[str(tag)] = count
        menu_sorted = sorted(menu.items(), key=lambda x:x[1], reverse=True)
        return dict(menu_sorted)

    def sort_like(self):
        posts = Post.objects.order_by('-like')
        return posts

    def sort_views(self):
        posts = Post.objects.order_by('-views')
        return posts
    


class Comment(models.Model):
    text = models.TextField()
    posted_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.text

app/posts/forms.py
from django import forms
from .models import Post
from django.forms import ModelForm

class PostAddForm(forms.ModelForm):    
   class Meta:
       model = Post
       fields = ['title', 'tags', 'body', 'image', 'btc']
       

app/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView
from .models import Post
from .models import Comment
from django.urls import reverse_lazy
from .forms import PostAddForm
from django.http.response import JsonResponse
from django.db.models import Q, Sum
from django.contrib import messages
from functools import reduce
from operator import and_
from taggit.models import Tag


def search_keyword(keyword, posts):
    exclusion_list = set([' ', '　'])
    q_list = ''
    for word in keyword:
        if word in exclusion_list:
            pass
        else:
            q_list += word

    query = reduce(
        and_, [Q(title__icontains=q) | Q(body__icontains=q)
                for q in q_list]
    )
    posts = posts.filter(query)
    return posts

def index(request):
    posts = Post.objects.order_by('-published')
    posts_filter = Post.objects.filter(author=request.user.id)
    posts_like = posts_filter.aggregate(Sum('like'))
    posts_views = posts_filter.aggregate(Sum('views'))
    keyword = request.GET.get('keyword')
    if keyword:
        posts = search_keyword(keyword, posts)
        messages.success(request, '「{}」の検索結果'.format(keyword))
        return render(request, 'posts/index.html', {'posts': posts, 'posts_count': len(posts_filter), 'posts_filter': posts_filter, 'posts_like': posts_like['like__sum'], 'posts_views': posts_views['views__sum']})
    else:
        return render(request, 'posts/index.html', {'posts': posts, 'posts_count': len(posts_filter), 'posts_filter': posts_filter, 'posts_like': posts_like['like__sum'], 'posts_views': posts_views['views__sum']})


def about(request):
    return render(request, 'posts/about.html')


def top(request):
    posts = Post.objects.order_by('-published')
    posts_filter = Post.objects.filter(author=request.user.id)
    posts_like = posts_filter.aggregate(Sum('like'))
    posts_views = posts_filter.aggregate(Sum('views'))
    keyword = request.GET.get('keyword')
    if keyword:
        posts = search_keyword(keyword, posts)
        messages.success(request, '「{}」の検索結果'.format(keyword))
        return render(request, 'posts/index.html', {'posts': posts})
    else:
        return render(request, 'posts/top.html', {'posts': posts, 'posts_count': len(posts_filter), 'posts_filter': posts_filter, 'posts_like': posts_like['like__sum'], 'posts_views': posts_views['views__sum']})

def get_posts_count(request, username):
    posts = Post.objects.filter(author=request.user.id)
    return JsonResponse({'posts_count': len(posts)})
    

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.views += 1
    post.save()
    keyword = request.GET.get('keyword')
    if keyword:
        posts = search_keyword(keyword, Post.objects.order_by('-published'))
        messages.success(request, '「{}」の検索結果'.format(keyword))
        return render(request, 'posts/index.html', {'posts': posts})
    else:
        if request.method == "POST":
            Comment.objects.create(text=request.POST["text"], article=post)
        return render(request, 'posts/post_detail.html', {'post': post})


def add(request):
    if request.method == "POST":
        form = PostAddForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            return redirect('posts:index')
    else:
        form = PostAddForm()
    return render(request, 'posts/add.html', {'form': form})


def edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = PostAddForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post.author = request.user
            form.save()
            return redirect('posts:post_detail', post_id=post.id)
    else:
        form = PostAddForm(instance=post)
    return render(request, 'posts/edit.html', {'form': form, 'post': post})


def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user == post.author:
        post.delete()
    return redirect('posts:index')


def like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.like += 1
    post.save()
    return redirect('posts:post_detail', post_id)


def api_like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.like += 1
    post.save()
    return JsonResponse({"like": post.like})


def categol_list(request, categol):
    posts = Post.objects.filter(tags__name__in=[categol])
    posts_filter = Post.objects.filter(author=request.user.id)
    posts_like = posts_filter.aggregate(Sum('like'))
    posts_views = posts_filter.aggregate(Sum('views'))
    keyword = request.GET.get('keyword')
    if keyword:
        posts = search_keyword(keyword, posts)
        messages.success(request, '「{}」の検索結果'.format(keyword))
        return render(request, 'posts/index.html', {'posts': posts, 'posts_count': len(posts_filter), 'posts_filter': posts_filter, 'posts_like': posts_like['like__sum'], 'posts_views': posts_views['views__sum']})
    else:
        return render(request, 'posts/index.html', {'posts': posts, 'posts_count': len(posts_filter), 'posts_filter': posts_filter, 'posts_like': posts_like['like__sum'], 'posts_views': posts_views['views__sum']})

app/posts/templates/posts/add.html
<!DOCTYPE html>
<html lang="ja-jp">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'posts/css/index.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'posts/images/favicon.ico' %}">
    <title>CreHub</title>
</head>

<body>
    <div class="header">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="{% static 'posts/images/te-logo.png' %}" class="img-fluid rounded"
                        style="max-height: 55px" /></a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                    data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <div class="navbar-item">
                        <div class="field is-grouped">
                        </div>
                    </div>

                </div>

                <div class="navbar-end">
                    {% if user.id %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            {{ user.username }}
                        </a>

                        <div class="navbar-dropdown is-right">
                            <a class="navbar-item">
                                マイページ
                            </a>
                            <a class="navbar-item" href="{% url 'posts:add' %}">
                                記事を書く
                            </a>
                            <a class="navbar-item">
                                アクセス解析
                            </a>
                            <hr class="navbar-divider">
                            <a class="navbar-item" href="{% url 'accounts:logout' %}">
                                ログアウト
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-primary" href="{% url 'accounts:signup' %}">
                                <strong>ユーザー登録</strong>
                            </a>
                            <a class="button is-light" href="{% url 'accounts:login' %}">
                                ログイン
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </nav>
    </div>
    <br /><br />
    <form action="{% url 'posts:add' %}" method="POST" enctype="multipart/form-data">
        {{ form.non_field_errors }}
        {% csrf_token %}
        {% for field in form %}
        <div class="signup">
            {{ form.media }}
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
            <span class="helptext">{{ field.help_text }}</span>
            {% endif %}
            {{ field.errors }}
        </div>
        {% endfor %}

        <br /><br />

        <div class="post-article">
            <button class="button is-info" type="submit">投稿する</button>
        </div>
        <br /><br />
    </form>


    <footer class="footer">
        <div class="content has-text-centered">
            <p>
                <strong>CreHub</strong>
            </p>
        </div>
    </footer>
</body>
<script src="{% static 'mdeditor/languages/en.js' %}"></script>
</html>

app/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="ja-jp">
{% load markdown_extras %}
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script src="https://use.fontawesome.com/releases/v5.3.1/js/all.js" defer></script>
    <script src="{% static 'posts/js/tabs.js' %}"></script>
    <script src="{% static 'posts/js/burger.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" href="{% static 'posts/css/index.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'posts/images/favicon.ico' %}">
    <link href="{% static 'posts/mdeditor/css/editormd.min.css' %}" rel="stylesheet">
    <link href="{% static 'posts/mdeditor/css/editormd.preview.css' %}" rel="stylesheet">
</head>

<body>
    <div class="header">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="{% static 'posts/images/te-logo.png' %}" class="img-fluid rounded"
                        style="max-height: 55px" /></a>

                <a role="button" class="navbar-burger" data-target="navMenu" aria-label="menu" aria-expanded="false">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navMenu" class="navbar-menu">
                <div class="navbar-start">
                    <div class="navbar-item">
                        <div class="field is-grouped">
                            <form action="" method="get">
                                <div class="control">
                                    <input class="input" name="keyword" type="text" placeholder="キーワードを入力">
                                </div>
                                <div class="control">
                                    <button class="button is-primary" type="submit"><i
                                            class="fa fa-search"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <div class="navbar-end">
                    {% if user.id %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            {{ user.username }}
                        </a>

                        <div class="navbar-dropdown is-right">
                            <a class="navbar-item" href="{% url 'posts:add' %}">
                                記事を書く
                            </a>
                            <hr class="navbar-divider">
                            <a class="navbar-item" href="{% url 'accounts:logout' %}">
                                ログアウト
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-primary" href="{% url 'accounts:signup' %}">
                                <strong>ユーザー登録</strong>
                            </a>
                            <a class="button is-light" href="{% url 'accounts:login' %}">
                                ログイン
                            </a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    <footer class="footer">
        <p>CreHub</p>
    </footer>
</body>

</html>

app/posts/templates/posts/edit.html
<!DOCTYPE html>
<html lang="ja-jp">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <link rel="stylesheet" href="{% static 'posts/css/index.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'posts/images/favicon.ico' %}">
    <title>CreHub</title>
</head>

<body>
    <div class="header">
        <nav class="navbar" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="/">
                    <img src="{% static 'posts/images/te-logo.png' %}" class="img-fluid rounded"
                        style="max-height: 55px" /></a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                    data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>

            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <div class="navbar-item">
                        <div class="field is-grouped">
                        </div>
                    </div>

                </div>

                <div class="navbar-end">
                    {% if user.id %}
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                            {{ user.username }}
                        </a>

                        <div class="navbar-dropdown is-right">
                            <a class="navbar-item">
                                マイページ
                            </a>
                            <a class="navbar-item" href="{% url 'posts:add' %}">
                                記事を書く
                            </a>
                            <a class="navbar-item">
                                アクセス解析
                            </a>
                            <hr class="navbar-divider">
                            <a class="navbar-item" href="{% url 'accounts:logout' %}">
                                ログアウト
                            </a>
                        </div>
                    </div>
                    {% else %}
                    <div class="navbar-item">
                        <div class="buttons">
                            <a class="button is-primary" href="{% url 'accounts:signup' %}">
                                <strong>ユーザー登録</strong>
                            </a>
                            <a class="button is-light" href="{% url 'accounts:login' %}">
                                ログイン
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </nav>
    </div>
    {% load markdown_extras %}
    {% if user.username == post.author|stringformat:"s" %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
        {% if field.name != 'author' and field.name != 'published' %}
        <div class="signup">
            {{ form.media }}
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
            <span class="helptext">{{ field.help_text }}</span>
            {% endif %}
            {{ field.errors }}
        </div>
        {% endif %}
        {% endfor %}
        <div class="post-article">
            <button class="button is-info" type="submit">編集する</button>
        </div>
        <br /><br />
    </form>
    {% endif %}
    <footer class="footer">
        <div class="content has-text-centered">
            <p>
                <strong>CreHub</strong>
            </p>
        </div>
    </footer>
</body>
<script src="{% static 'mdeditor/languages/en.js' %}"></script>

</html>

app/posts/templates/posts/index.html
{% extends './base.html' %}
{% block content %}
{% load static %}
{% load markdown_extras %}
{% if messages %}
<div class="search-result" style="margin-top:1rem;">
    <div class="message is-success">
        <div class="message-body">
            {% for message in messages %}
            <p> {{ message }}</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}
<div class="main-contents">
    <div class="categolize-icon">
        <span class="icon has-text-info">
            <i class="fas fa-tag" aria-hidden="true" style="color: rgb(50, 231, 177);"></i>
        </span>
        <span>タグ一覧</span>
    </div>
    <div class="categolize-menu">
        <aside class="menu">
            <ul class="menu-list">
                <hr class="navbar-divider">
                {% for post in posts.all|slice:":1" %}
                {% for tag, num in post.get_tags.items %}
                <li>
                    <span><a href="{% url 'categol_list' tag %}">{{ tag }}{{ num }}</a></span>

                </li>
                <hr class="navbar-divider">
                {% endfor %}
                {% endfor %}
            </ul>
        </aside>
    </div>
    <br />
    <div class="user-card">
        <div class="card-icon">
            <span class="icon has-text-info">
                <i class="fas fa-address-card" aria-hidden="true" style="color: rgb(50, 231, 177);"></i>
            </span>
            <span>マイカード</span>
        </div>
        <div class="card">
            <div class="card-image">
            </div>
            {% if user.id %}
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-64x64">
                            <img class="is-rounded" src="{% static 'posts/images/top-image.png' %}">
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">{{ user.username }}</p>
                        <p class="subtitle is-6">@userid</p>
                    </div>
                </div>
                <div class="content">

                    <p>投稿数 : 0</p>
                    <p>いいね数 : 0</p>
                    <p>ブックマーク数 : 0</p>
                    <p>総アクセス数 : 0</p>
                    <hr>
                    <a href="{% url 'posts:add' %}">
                        <strong>記事を書く</strong>
                    </a>
                </div>
            </div>
            {% else %}
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-64x64">
                            <img class="is-rounded" src="{% static 'posts/images/logo3.png' %}">
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">ゲスト</p>
                        <p class="subtitle is-6">@userid</p>
                    </div>
                </div>
                <div class="content">
                    <p>投稿数 : {{ post.count }} </p>
                    <p>いいね数 : 0</p>
                    <p>ブックマーク数 : 0</p>
                    <p>総アクセス数 : 0</p>
                    <hr>
                    <a href="{% url 'accounts:signup' %}">
                        <strong>記事を書く</strong>
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>

    <div class="containers">
        <section class="hero">
            <div class="hero-foot">
                <nav class="tabs is-toggle">
                    <div class="container">
                        <span class="icon has-text-info">
                            <i class="fas fa-chart-line" aria-hidden="true" style="color: rgb(50, 231, 177);"></i>
                        </span>
                        <span>トレンド</span>
                        <ul>
                            <li class="tab is-active" onclick="openTab(event,'WebDev')"><a>今日</a></li>
                            <li class="tab" onclick="openTab(event,'WebAud')"><a>今週</a></li>
                            <li class="tab" onclick="openTab(event,'Support')"><a>今月</a></li>
                            <li class="tab" onclick="openTab(event,'All')"><a>全期間</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </section>
        <div class="container section">
            <div id="WebDev" class="content-tab">
                {% for post in posts.all%}
                <div class="box">
                    <article class="media">
                        <a href="{% url 'post_detail' post.id %}">
                            <div class="media-left">
                                {% if post.image %}
                                <figure class="image is-64x64">
                                    <img src="{{ post.image.url }}" alt="Image">
                                </figure>
                                {% endif %}
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <strong>{{ post.title }}</strong><br>
                                    <small>{{ post.published }}</small>
                                    <small>{{ post.author }}</small>
                                    {% for tag in post.tags.all %}
                                    <button class="button is-success is-small is-rounded">{{ tag }}</button>                                    {% endfor %}
                                    <br>
                                    {{ post.summary|markdown|safe }}
                                </div>
                                <nav class="level is-mobile">
                                    <div class="level-left">
                                        <p><span id="like" style="font-weight:normal;">{{ post.like }}</span>いいね！</p>
                                        <a class="level-item" aria-label="like">
                                            <span class="icon is-small has-text-info">
                                                <i class="fas fa-star" aria-hidden="true"
                                                    style="color: rgb(50, 231, 177);"></i>
                                            </span>
                                        </a>
                                    </div>
                                </nav>
                            </div>
                    </article>
                    </a>
                </div>

                {% endfor %}
            </div>
            <div id="WebAud" class="content-tab" style="display:none">
                <p>
                    test2<br>
                    Details Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
                    been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley
                    of type and scrambled it to make a type specimen book. It has survived not only five centuries, but
                    also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in
                    the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently
                    with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            </div>
            <div id="Support" class="content-tab" style="display:none">
                <p>
                    test3 <br>
                    Specification Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
                    has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a
                    galley of type and scrambled it to make a type specimen book. It has survived not only five
                    centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was
                    popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and
                    more recently with desktop publishing software like Aldus PageMaker including versions of Lorem
                    Ipsum.</p>
            </div>
            <div id="All" class="content-tab" style="display:none">
                <p>
                    all</p>
            </div>
        </div>

        <br />
    </div>
</div>
{% endblock %}